@echo off
echo Starting Macro Project (Team RAGTAG)...

echo Starting Backend (Flask)...
start "Flask Backend" cmd /c "cd backend && .\venv\Scripts\activate && python app.py"

echo Starting Frontend (Next.js)...
start "Next.js Frontend" cmd /c "cd frontend && npm run dev"

echo Waiting for servers to initialize...
timeout /t 5 > nul

echo Opening browser...
start http://localhost:3000
